# .af/config.yml
root: .
models:
  default: Qwen/Qwen2.5-Coder-32B-Instruct
  bigPlan: deepseek-ai/DeepSeek-V3
actions:
  shell:
    allow: [node, npm, pnpm, npx, git, af, vercel, supabase, railway]
routing:
  snapshotBytesThreshold: 700000
  planFileCountThreshold: 1500
check:
  typecheck: npx tsc -p tsconfig.json --noEmit
  lint: npx eslint "src/**/*.ts" "vscode-extension/src/**/*.ts"
  test: npx vitest run --reporter=dot --coverage
deploy:
  vercel: true
  supabase: true
  railway: false

