# .af/config.yml
root: .                       # required by schema; project root
models:
  default: deepseek-ai/DeepSeek-V3
  bigPlan: meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo
actions:
  shell:
    allow: [node, npm, pnpm, npx, git, af]   # safe allowlist for tools
routing:
  snapshotBytesThreshold: 700000
  planFileCountThreshold: 1500
check:
  typecheck: npx tsc -p tsconfig.json --noEmit
  lint: npx eslint "src/**/*.ts" "vscode-extension/src/**/*.ts"
  test: npx vitest run --reporter=dot --coverage